# -*- coding: utf-8 -*-
"""muhrakhaal-testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCKehFopEnkUnR_kWd13Gp9kBoeKXQO_

# **Proyek Pengembangan Machine Learning Pipeline :**
- **Nama:** Muhammad Rakha Almasah
- **Email:** muh.rakha.al@gmail.com
- **ID Dicoding:** muhrakhaal

# **Tahap 4 : Tes Server**
"""

import requests
FLASK_SERVER_URL = "https://a227-34-172-17-139.ngrok-free.app/predict"
data = {
    "features": {
        "AAPL": [111.28],
        "MSFT": [336.32],
        "AMZN": [138.12],
        "BRK_B": [553.50],
        "IXIC": [0.0]
    }
}

response = requests.post(FLASK_SERVER_URL, json=data)

if response.status_code == 200:
    print("Hasil Prediksi:", response.json()["predictions"])
else:
    print("Error:", response.text)